increment_3 initial
dupreehkuda/url-shortener pull request #3
Opened 2022-07-13 07:34 UTC by dupreehkuda

2022-07-14 11:38 UTC, bambruysk requested changes
мердж должен быть из инкремента в мейн

2022-07-14 11:38 UTC, bambruysk commented on internal/server/server.go
> +	// здесь хотел прописать эндпоинты, но не придумал как притянуть storage
server может быть структурой, к которой привязываются методы. в ней же может быть ссылка на storage

2022-07-14 11:38 UTC, bambruysk commented on internal/handlers/handlers.go
> +		string := fmt.Sprintf("http://localhost:8080/%v", len(storage))
называть переменную так же как и встроенный тип можно, но не очень хорошо, что это за строка?

2022-07-14 11:38 UTC, bambruysk commented on internal/handlers/handlers.go
> +		storage[len(storage)+1] = string(b)
Если выполнить одновременно два запроса, то тут потенциальная паника. Запросы обрабатываются в отдельных горутинах.  А map не потокобезопасен. Хранилище в целом лучше оформить как отдельный слой, что если мы изменим метод хранения?
А если нужно будет удалять  url. из хранилища?

2022-07-14 11:38 UTC, bambruysk commented on internal/handlers/handlers.go
> +func PostShorten(storage map[int]string) gin.HandlerFunc {
Экспортируемые переменные, типы и функции должны быть прокмментированы. Линтер должен поругаться на это

2022-07-14 11:38 UTC, bambruysk commented on internal/handlers/handlers.go
> +			return
Не стоит пренебрегать логгированием. Оно очень полезно. 
Здесь мы пользоватедю что-то возращаем?

2022-07-14 11:38 UTC, bambruysk commented on cmd/shortener/main.go
> +	r.GET("/:id", handlers.GetShortened(storage.Shortened))
все это можно запихнуть в слой API

2022-07-14 15:37 UTC, dupreehkuda commented on internal/handlers/handlers.go
> +		storage[len(storage)+1] = string(b)
Можете тогда подсказать как лучше хранить данные? Слайс просто?

2022-07-14 15:39 UTC, dupreehkuda commented on internal/handlers/handlers.go
> +func PostShorten(storage map[int]string) gin.HandlerFunc {
Хорошо, а какой линтер вы посоветуете? Я попробовал golangci-lint, о котором в слаке писали, но он не отметил это.

2022-07-21 17:25 UTC, bambruysk approved these changes
Поправить одно маленькое замечаение и можно сливтаь

2022-07-21 17:25 UTC, bambruysk commented on internal/storage/storage.go
> +	return s.shortened[id], nil
Чтение из мапы тоже должно бтыь защищено мьютексом  - здесь подойде RLock()/RUnlock

2022-07-22 10:13 UTC, merged